### DISCUSSION TITLE
How to highlight active items in Submenus

### DISCUSSION THREAD

**Discussion by drixie** [ariakit/ariakit#944] [Questions] [answered]
In the sample code here, active parent items are highlighted with a blue background - https://reakit.io/docs/menu/#submenu

I am looking for information about which prop will allow me to access parent items that are currently active in nested submenus

**Comment by diegohaz** [comment, marked as answer]
@drixie The example is just using the `[aria-expanded="true"]` selector to style the active item.

```css
.menu-item-class-name[aria-expanded="true"] {
  background: blue;
}
```
