### ISSUE TITLE
Select combobox example flashes focus outline on click

### ISSUE THREAD

**Issue by IngoValente** [ariakit/ariakit#1257]
### Current behavior

Super tiny change, but I think it looks better while still being accessible.
Current behaviour:
When the select has no focus, clicking on it will flash the outline for a sec, and then outline the combobox input in the opened popup.

https://user-images.githubusercontent.com/4366126/164268420-39570986-d64f-439a-9667-4b676cf049db.mov

### Steps to reproduce the bug

1. Open ariakit example: https://ariakit.org/examples/select-combobox
2. Click on the select while it has no focus
3. See the outline flash
(Firefox on mac)

### Expected behavior

In this case, because we always focus the combobox input on click, I think we can skip the select input outline. On keyboard focus, it should still become visible (because the popover is not open yet)

https://user-images.githubusercontent.com/4366126/164269098-5fcbf345-a37b-4ee9-8a4b-f8cb47cebb42.mov

### Possible solutions

This is a simple styling fix. The current style has the following outline code:
```css
.select:focus-visible,
.select[data-focus-visible],
.popover:focus-visible,
.popover[data-focus-visible] {
  outline: 2px solid hsl(204, 100%, 40%);
}
```

By removing  `.select[data-focus-visible]` I get the desired result.
