### ISSUE TITLE
Animated dialog not closing

### ISSUE THREAD

**Issue by kwiat1990** [ariakit/ariakit#1591]
### Current behavior

I'm moving to a simpler setup with Tailwind and Ariakit, so I replace the code component for component. I wanted to replace a modal. As the currently is animated I copied code from https://ariakit.org/examples/dialog-animated and it is broken as I can't close the dialog. Neither click on dismiss button nor on button in dialog's footer or backdrop does work.

After removing animated param from `useDialogState()` hook everything works.

What's odd, the example with animated dialog on docs site does work.

This is related to https://github.com/ariakit/ariakit/issues/1357.

Details:
Browser: `Version 103.0.5060.53 (Official Build) (x86_64)`
Ariakit: `^2.0.0-next.32`

### Steps to reproduce the bug

Open this code sandbox: https://codesandbox.io/s/ariakit-forked-hnnu0g

### Expected behavior

Dialog can be closed on click on following elements: dismiss button, a button calling `dialog.hide` method or backdrop.

### Workaround

Using not animated version of the dialog.

**Comment by diegohaz** [comment]
The `animated` prop is a way to tell the library that you're performing an animation on the dialog. Ariakit uses this information to delay the initial focus until the enter animation is complete and keep the dialog visible until the exit animation is done. *It does not animate the dialog for you*.

There are several ways to animate the dialog. The simplest one is with CSS:

```css
.dialog {
  opacity: 0;
  transform: translate(-50%, -60%);
  transition-duration: 300ms;
  transition-timing-function: cubic-bezier(0.4, 0, 1, 1);
}

.dialog[data-enter] {
  transform: translate(-50%, -50%);
  opacity: 1;
}
```
