### ISSUE TITLE
Modal backdrop covers modal

### ISSUE THREAD

**Issue by IanVS** [ariakit/ariakit#2484]
### Current behavior

I'm in the process of upgrading from ariakit to @ariakit/react, and found that I'm having trouble with my modals.  The backdrop is covering the modal itself, causing the inputs to not be focusable, and the color of the backdrop bleeds over the modal body.  I think this is because I'm not using `position: fixed` for my modal, since it was not required previously.  Is it a requirement now?

### Steps to reproduce the bug

1. Open sandbox: https://codesandbox.io/s/ariakit-dialog-backdrop-8l5891?file=/src/styles.css
2. Notice that the backdrop covers the modal, and the input cannot be clicked

### Expected behavior

The backdrop should be behind the modal.

### Workaround

This only seems to happen when not using `position: fixed` for the modal.

**Comment by IanVS** [comment]
It seems like the main change causing me problems is that previously, the modal body was a child of the fixed-position overlay.  Now it's a sibling.  I'm having a bit of difficulty re-creating my previous behavior or being able to add scroll to the overlay, allowing the entire modal to scroll up and down as needed (see https://codesandbox.io/s/ariakit-dialog-backdrop-old-style-bcmiol for an example).  Do you know how to re-create that effect using the current version?

**Comment by diegohaz** [comment]
Yeah, the backdrop element is now a sibling of the dialog. This is to allow them to be animated separately. For example, you can fade in the backdrop later than showing the dialog itself. It's not possible if the dialog is wrapped within the backdrop.

I recommend the following base styles for the dialog, which are based on the styles the browser applies to native modal dialogs:

```css
.dialog {
  position: fixed;
  inset: 1rem;
  margin: auto;
  height: fit-content;
  max-height: calc(100vh - 2 * 1rem);
}
```

If you want to stick with the old style, you can do so by disabling the default backdrop and rendering your own wrapper using the `render` prop:

https://codesandbox.io/s/ariakit-dialog-backdrop-old-style-o4zle5?file=/src/App.tsx

```jsx
<Dialog
  store={dialogStore}
  backdrop={false}
  className="modal"
  render={(props) => (
    <div className="modal-overlay">
      <div {...props} />
    </div>
  )}
>
  <div className="modal-contents">
    <div>A tall modal, can scroll down to see the entire thing. </div>
  </div>
</Dialog>
```

**Comment by IanVS** [comment]
Thanks for the detailed suggestion and workaround.  I think the main downside I can see to the approach you suggest to use the `render` prop, is that the `hideOnInteractOutside` won't work, since the entire modal overlay is considered to be part of the `contentElement`, right?  I'm working on finding a way to make it work, so far getting stymied at the check for whether the element is "marked".  I'll report back if I figure something out, for anyone else hitting this.

**Comment by diegohaz** [comment]
Which version are you using? There was a recent update on the marked logic (mostly for popover wrappers, but should also take custom backdrop wrapper elements into account).

In the CodeSandbox I sent above, clicking on the backdrop does hide the dialog.

**Comment by Dremora** [comment]
I've encountered a rather tricky scenario, I want to animate both backdrop and modal and close the modal on outside click. After some tinkering, this is what helped me:

1) kept backdrop
2) used `render` prop and spread props on the nested element
3) provided `pointer-events: none` on the outside element passed to `render`
4) `children` is simply modal contents

```typescript
<AriakitDialog
  store={store}
  backdrop={<div className="backdrop />}
  render={(dialog) => (
    <div className="modal-container">
      <div className="modal" {...dialog} />
    </div>
  )}
>
  {children}
</AriakitDialog>
```

```css
.backdrop {
  /* add backdrop animations here */
}

.modal-container {
  /* note that this element renders no visible UI, but it's not managed by Ariakit,
    meaning it will block user interactions when the modal is hidden */
  pointer-events: none;
  margin: auto;
  position: fixed;
  inset: 0;
  /* adjust spacing here as necessary */
}

.modal {
  pointer-events: auto;
  margin: auto;
  /* add modal animations here */
}
```

Hope this is useful!
