### ISSUE TITLE
Consider setting ‘min-width’ with ‘sameWidth’ for popovers

### ISSUE THREAD

**Issue by kripod** [ariakit/ariakit#3805]
### Motivation

Currently, the `sameWidth` prop of popovers set the `width` CSS property as shown: https://github.com/ariakit/ariakit/blob/7aa3bc6c9be4b515fc3ed73c938236b182bd0395/packages/ariakit-react-core/src/popover/popover.tsx#L184-L186

Usually, a popover has an arbitrary minimum width like 320px, compensating for the shrinking effect of a small anchor. Currently, Ariakit endorses the [`min()` CSS function](https://developer.mozilla.org/en-US/docs/Web/CSS/min) as follows:

```css
/* Wrapper has `width: var(--popover-anchor-width)` */
.popover {
  /* `width` set on the wrapper becomes redundant */
  width: min(320px, var(--popover-anchor-width));
}
```

However, by setting `min-width` instead of `width` on the wrapper via `sameWidth`, the user-land styling could be simplified:

```css
/* Wrapper has `min-width: var(--popover-anchor-width)` */
.popover {
  width: 320px;
  max-width: var(--popover-available-width);
}
```

Assuming that `var(--popover-available-width)` is always greater than or equal to both `var(--popover-anchor-width)` and `320px`, the available width should be assigned to `max-width`, which is what `fitViewport` already does.

On the other hand, for `width` and `min-width`, we have two scenarios:

1. `width: var(--popover-anchor-width)` _(current behavior)_ with `min-width: 320px`
   Being cautious about [`min-width` always overriding `max-width`](https://css-tricks.com/almanac/properties/m/max-width/), this may break on smaller screens, as a width of at least 320px would be enforced regardless of having `max-width: var(--popover-available-width)`.

2. `min-width: var(--popover-anchor-width)` _(proposed behavior)_ with `width: 320px`
   In case `min-width` is smaller than 320px, the minimum width gets limited to `var(--popover-anchor-width)`, while the arbitrary `width` is constrained by `max-width: var(--popover-available-width)` to prevent overflow. Therefore, this behavior should be more responsive in general.

### Usage example

N/A

### Requirements

Popover wrappers should have their `min-width` set (instead of `width`) when the `sameWidth` prop is specified,

### Workaround

Instead of using the `sameWidth` prop on popovers, apply a `className` similar to the result of these [Tailwind CSS](https://tailwindcss.com/) utilities:

```diff
<Popover
- sameWidth
+ className="w-80 min-w-[--popover-anchor-width] max-w-[--popover-available-width]"
>
  …
</Popover>
```

### Possible implementations

Change [this snippet](https://github.com/ariakit/ariakit/blob/7aa3bc6c9be4b515fc3ed73c938236b182bd0395/packages/ariakit-react-core/src/popover/popover.tsx#L184-L186) as follows:

```diff
- wrapper.style.width = `${referenceWidth}px;
+ wrapper.style.minWidth = `${referenceWidth}px;
```
