### ISSUE TITLE
Popover-based components: expose computed popover placement

### ISSUE THREAD

**Issue by ciampo** [ariakit/ariakit#4082]
### Motivation

When animating a popover, knowing the placement can help to create an animation with directional awareness.

While it is currently possible to somehow get the placement (maybe by intercepting the `placement` prop while forwarding it to the store, or reading it from state), that placement doesn't take writing direction and potential layout transformations (ie. flipping the popover for lack of screen estate). In those instances, the animation may end disconnected with the "computed" popover placement.

### Usage example

Assuming the placement's `side` is reflected via a data-attribute, a consumer could use that information to animate the popover accordingly:

```css

.popover[data-open] {
	@media not ( prefers-reduced-motion ) {
		animation-duration: ${ ANIMATION_PARAMS.DURATION };
		animation-timing-function: ${ ANIMATION_PARAMS.EASING };
		will-change: transform, opacity;
		&[data-open-side='bottom'] {
			transform-origin: top;
			animation-name: slide-down-and-fade;
		}
		&[data-open-side='left'] {
			transform-origin: right;
			animation-name: slide-left-and-fade;
		}
		&[data-open-side='top'] {
			transform-origin: bottom;
			animation-name: slide-up-and-fade;
		}
		&[data-open-side='right'] {
			transform-origin: left;
			animation-name: slide-right-and-fade;
		}
	}
}

```

### Requirements

The computed placement should be available either via store state, or exposed as a data attribute (ie. `data-open-side-[sideName]`)

### Workaround

While it's technically possible to adjust for writing direction by manually swapping `left` and `right`, a consumer of the component currently doesn't have access to floating UI's final computed placement, and therefore "flip"s are impossible to detect.
